package com.example.vuldetect;

public class Config {

    public static final String AZR_AZ = "az";
    public static final String AZR_LOGIN = "login";
    public static final String AZR_STORAGE = "storage";
    public static final String AZR_ACCOUNT = "account";
    public static final String AZR_LIST = "list";
    public static final String AZR_KEYS = "keys";
    public static final String AZR_0_VALUE = "[0].value";
    public static final String AZR_ENABLED = "enabled";
    public static final String AZR_CONFIG = "config";
    public static final String AZR_BLOB = "blob";
    public static final String AZR_TABLE = "table";
    public static final String AZR_SERIVCE_PROPERTIES = "service-properties";
    public static final String AZR_DELETE_POLICY = "delete-policy";
    public static final String AZR_SHOW = "show";
    public static final String AZR_READ = "read";
    public static final String AZR_DELETE = "delete";
    public static final String AZR_WRITE = "write";
    public static final String AZR_LOGGING = "logging";
    public static final String AZR_RESOURCEGROUP = "--resource-group";
    public static final String AZR_DASH_NAME = "--name";
    public static final String AZR_QUERY = "--query";
    public static final String AZR_ACCOUNT_NAME = "--account-name";
    public static final String AZR_ACCOUNT_KEY = "--account-key";
    public static final String AZR_AUTH_MODE = "--auth-mode";
    public static final String AZR_ALLOW_NO_SUBSCRIPTIONS = "--allow-no-subscriptions";
    public static final String AZR_SERVICE = "--service";
    public static final String AZR_T = "t";
    public static final String AZR_B = "b";
    public static final String AZR_N = "-n";
    public static final String AZR_G = "-g";
    public static final String AZR_KEYPOLICY = "keyPolicy";
    public static final String AZR_KEYEXPIRATIONPERIODINDAYS = "keyExpirationPeriodInDays";
    public static final String AZR_NETWORKRULESET = "networkRuleSet";
    public static final String AZR_NAME = "[*].name";
    public static final String AZR_DEFAULTACTION = "defaultAction";
    public static final String AZR_DENY = "Deny";
    public static final String AZR_BYPASS = "bypass";
    public static final String AZR_AZURESERVICES = "AzureServices";
    public static final String AZR_WEBAPP = "webapp";
    public static final String AZR_CLIENTCERTENABLED = "clientCertEnabled";
    public static final String AZR_HTTPSONLY = "httpsOnly";
    public static final String AZR_MINTLSVERSION = "minTlsVersion";
    public static final String AZR_IDENTITY = "identity";
    public static final String AZR_PRINCIPALID = "principalId";
    public static final String AZR_RANDOMVALUE = "randomValue";
    public static final boolean AZR_TRUE = true;
    public static final boolean AZR_FALSE = false;

    public static final String DGNSS_ENTITY_KEY = "dgnssEntityKey";
    public static final String DGNSS_ENTITY_STATUS = "dgnssEntityStatus";
    public static final String AZR_SECURITY = "security";
    public static final String AZR_PRICING = "pricing";
    public static final String AZR_VIRTUALMACHINES = "VirtualMachines";
    public static final String AZR_SETTING = "setting";
    public static final String AZR_MCAS = "MCAS";
    public static final String AZR_MONITOR = "monitor";
    public static final String AZR_ALERT = "alert";
    public static final String AZR_SUBSCRIPTION = "--subscription";
    public static final String AZR_074WRITECONDITIONS = "[?condition.allOf[?equals == 'Microsoft.Authorization/policyAssignments/write']]";
    public static final String AZR_076WRITECONDITIONS = "[?condition.allOf[?equals == 'Microsoft.Network/networkSecurityGroups/write']]";
    public static final String AZR_078WRITECONDITIONS = "[?condition.allOf[?equals == 'Microsoft.Network/networkSecurityGroups/securityRules/write']]";
    public static final String AZR_080WRITECONDITIONS = "[?condition.allOf[?equals == 'Microsoft.Security/securitySolutions/write']]";
    public static final String AZR_082WRITECONDITIONS = "[?condition.allOf[?equals == 'Microsoft.Sql/servers/firewallRules/write']]";
    public static final String AZR_ACTIVITYLOG = "activity-log";
    public static final String AZR_SQLSERVERS = "SqlServers";
    public static final String AZR_STORAGEACCOUNTS = "StorageAccounts";
    public static final String AZR_APPSERVICES = "AppServices";
    public static final String AZR_KEYVAULTS = "KeyVaults";
    public static final String AZR_PRICINGTIER = "pricingTier";
    public static final String AZR_STANDARD = "Standard";
    public static final String AZR_FREE = "Free";
    public static final String IS_PASS = "isPass";
    public static final String AZR_023 = "AZR_023";
    public static final String AZR_024 = "AZR_024";
    public static final String AZR_025 = "AZR_025";
    public static final String AZR_027 = "AZR_027";
    public static final String AZR_030 = "AZR_030";
    public static final String AZR_032 = "AZR_032";
    public static final String AZR_041 = "AZR_041";
    public static final String AZR_042 = "AZR_042";
    public static final String AZR_043 = "AZR_043";
    public static final String AZR_044 = "AZR_044";
    public static final String AZR_045 = "AZR_045";
    public static final String AZR_047 = "AZR_047";
    public static final String AZR_074 = "AZR_074";
    public static final String AZR_076 = "AZR_076";
    public static final String AZR_078 = "AZR_078";
    public static final String AZR_080 = "AZR_080";
    public static final String AZR_082 = "AZR_082";
    public static final String AZR_106 = "AZR_106";
    public static final String AZR_107 = "AZR_107";
    public static final String AZR_108 = "AZR_108";
    public static final String AZR_109 = "AZR_109";

}
